version: '3.8'

services:
  ffc-grants-productivity-web:
    build:
      context: .
      target: production
    image: ffc-grants-productivity-web
    container_name: ffc-grants-productivity-web
    environment: {}
