version: '3.8'

services:
  ffc-grants-productivity-web:
    build:
      target: production
    image: ffc-grants-productivity-web
    container_name: ffc-grants-productivity-web
    
    environment: 
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PARTITION: ffc-grants-productivity
      REDIS_PASSWORD: ""
      SESSION_CACHE_TTL: 3600000
