environment: development
name: ffc-grants-productivity-web
namespace: ffc-grants
workstream: ffc-grants
image: ffc-grants-productivity-web

labels: {}

appInsights:
  key: not-a-real-key

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
  
containerConfigMap:
  name: ffc-grants-productivity-web-config-map

containerSecret:
  name: ffc-grants-productivity-web-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: high
  minReadySeconds: 2
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 30303
  replicas: 2
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  redisHostname: redis
  redisPassword: redis
  cookiePassword: thisisnotarealpasswordthisisnotarealpassword
  redisPort: 6379
  redisPartition: ffc-grants-productivity-web
  sessionCacheTTL: 3600000
  messageQueueHost: dummy
  projectDetailsQueueAddress: project-details
  contactDetailsQueueAddress: contact-details
  loginRequired: false
  authUsername: grants
  authPasswordHash: dummy
  backendPollingHost: http://ffc-grants-eligibility
  pollingInterval: 200
  pollingRetries: 20
  protectiveMonitoringUrl:
  googleTagManagerKey: dummy
  googleTagManagerServerKey: dummy
  startPageUrl: dummy

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

service:
  port: 80

ingress:
  class: nginx
  endpoint: ffc-grants-frontend
  server: example.com
  path: /productivity
